CFLAGS=-pedantic -Wall -Werror -ggdb3
all:cyoa-step1 cyoa-step2 cyoa-step3 cyoa-step4
cyoa-step1:cyoa-step1.cpp head.h
	g++ $(CFLAGS) -o cyoa-step1 cyoa-step1.cpp
cyoa-step2:cyoa-step2.cpp head.h
	g++ $(CFLAGS) -o cyoa-step2 cyoa-step2.cpp
